<#
.SYNOPSIS
Generate a multi-role assessment report from completed changes.

.DESCRIPTION
Simulates four review roles: Planner, Implementer, Tester, Reviewer.
Evaluates change completeness against agent-flow artifact requirements.

.PARAMETER ChangeDir
Single change directory to assess (optional; assesses all if omitted).

.PARAMETER Output
Output file path.

.PARAMETER ChangesRoot
Changes root directory (default: agent-flow/changes).
#>

param(
    [string]$ChangeDir = "",
    [string]$Output = "",
    [string]$ChangesRoot = "agent-flow/changes"
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $PSCommandPath
. (Join-Path $scriptDir "_common.ps1")

$dirs = @()
if ($ChangeDir -and (Test-Path $ChangeDir)) { $dirs = @($ChangeDir) }
else {
    $dirs = Get-ChildItem -Directory $ChangesRoot | Where-Object { $_.Name -ne '.gitkeep' }
}

$report = @"
# Multi-Role Assessment Report

Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')
Changes assessed: $($dirs.Count)

"@

foreach ($dir in $dirs) {
    $name = Split-Path $dir -Leaf
    $flow = Get-FlowLevel -Dir $dir
    $hasReport = Test-Path (Join-Path $dir "REPORT.md")
    $hasVerify = Test-Path (Join-Path $dir "VERIFY.md")
    $hasDesign = Test-Path (Join-Path $dir "DESIGN.md")
    $hasAudit = Test-Path (Join-Path $dir "AUDIT.md")
    $hasReview = Test-Path (Join-Path $dir "REVIEW.md")
    $hasEvolution = Test-Path (Join-Path $dir "EVOLUTION.md")

    $acCount = 0; $evCount = 0
    $reqFile = Join-Path $dir "REQUIREMENT.md"
    if (Test-Path $reqFile) {
        $acCount = (Select-String -Path $reqFile -Pattern 'AC-0\d' -AllMatches).Matches.Count
    }
    $verFile = Join-Path $dir "VERIFY.md"
    if (Test-Path $verFile) {
        $evCount = (Select-String -Path $verFile -Pattern 'AC-0\d' -AllMatches).Matches.Count
    }

    $coverage = if ($acCount -gt 0) { "$($evCount * 100 / $acCount)%" } else { 'N/A' }
    $artifactsDone = @($hasReport, $hasVerify, $hasDesign, $hasAudit, $hasReview, $hasEvolution).Where({ $_ -eq $true }).Count + 1

    $report += @"

## $name ($flow)

### Planner Assessment
- Artifacts complete: $artifactsDone/9
- Goals defined: $(if (Test-Path (Join-Path $dir "CHANGE.md")) { 'yes' } else { 'no' })

### Implementer Assessment
- Flow level: $flow
- Implementation complete: $(if ($hasVerify) { 'yes' } else { 'no' })

### Tester Assessment
- Acceptance criteria: $acCount defined, $evCount with evidence
- Coverage: $coverage

### Reviewer Assessment
- Design reviewed: $(if ($hasDesign) { 'yes' } else { 'no' })
- Audit completed: $(if ($hasAudit) { 'yes' } else { 'no' })
- Peer review: $(if ($hasReview) { 'yes' } else { 'no' })
- Evolution recorded: $(if ($hasEvolution) { 'yes' } else { 'no' })

---
"@
}

$report += @"

*Generated by _generate-assessment.ps1*
"@

if ($Output) { $report | Set-Content -Path $Output -Encoding utf8; Write-Host "Report written to: $Output" }
else { Write-Host $report }
