#!/usr/bin/env bash
# Generate a multi-role assessment report from completed changes.
# Simulates four review roles: Planner, Implementer, Tester, Reviewer.
# Usage: bash agent-flow/scripts/_generate-assessment.sh [--change-dir <dir>] [--output <file>]
set -euo pipefail

change_dir=""
output_file=""
changes_root="agent-flow/changes"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --change-dir|-ChangeDir) change_dir="$2"; shift 2 ;;
    --output|-Output) output_file="$2"; shift 2 ;;
    --changes-root|-ChangesRoot) changes_root="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--change-dir <dir>] [--output <file>] [--changes-root <dir>]"
      exit 0 ;;
    *) echo "Unknown: $1" >&2; exit 2 ;;
  esac
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/_common.sh"

# --- Collect changes to assess ---
dirs=()
if [ -n "$change_dir" ]; then
  dirs=("$change_dir")
else
  for d in "$changes_root"/*/; do
    [ -d "$d" ] && [ "$(basename "$d")" != ".gitkeep" ] && dirs+=("$d")
  done
fi

report="# Multi-Role Assessment Report

Generated: $(date '+%Y-%m-%d %H:%M')
Changes assessed: ${#dirs[@]}

"

for dir in "${dirs[@]}"; do
  name=$(basename "$dir")
  flow=$(flow_level "$dir")
  has_report=0; [ -f "$dir/REPORT.md" ] && has_report=1
  has_verify=0; [ -f "$dir/VERIFY.md" ] && has_verify=1
  has_design=0; [ -f "$dir/DESIGN.md" ] && has_design=1
  has_audit=0; [ -f "$dir/AUDIT.md" ] && has_audit=1
  has_review=0; [ -f "$dir/REVIEW.md" ] && has_review=1
  has_evolution=0; [ -f "$dir/EVOLUTION.md" ] && has_evolution=1

  # Count ACs from REQUIREMENT.md
  ac_count=0
  [ -f "$dir/REQUIREMENT.md" ] && ac_count=$(grep -c 'AC-0[0-9]' "$dir/REQUIREMENT.md" 2>/dev/null || echo 0)

  # Count evidence from VERIFY.md
  ev_count=0
  [ -f "$dir/VERIFY.md" ] && ev_count=$(grep -c 'AC-0[0-9]' "$dir/VERIFY.md" 2>/dev/null || echo 0)

  report+="## $name ($flow)

### Planner Assessment
- Artifacts complete: $(printf '%d/9' $((has_report + has_verify + has_design + has_audit + has_review + has_evolution + 1)) )
- Goals defined: $([ -f "$dir/CHANGE.md" ] && grep -q "目标" "$dir/CHANGE.md" && echo 'yes' || echo 'no')

### Implementer Assessment
- Flow level: $flow
- Implementation complete: $([ "$has_verify" = 1 ] && echo 'yes' || echo 'no')

### Tester Assessment
- Acceptance criteria: $ac_count defined, $ev_count with evidence
- Coverage: $([ "$ac_count" -gt 0 ] && echo "$(( ev_count * 100 / ac_count ))%" || echo 'N/A')

### Reviewer Assessment
- Design reviewed: $([ "$has_design" = 1 ] && echo 'yes' || echo 'no')
- Audit completed: $([ "$has_audit" = 1 ] && echo 'yes' || echo 'no')
- Peer review: $([ "$has_review" = 1 ] && echo 'yes' || echo 'no')
- Evolution recorded: $([ "$has_evolution" = 1 ] && echo 'yes' || echo 'no')

---
"
done

report+="
*Generated by _generate-assessment.sh*"

if [ -n "$output_file" ]; then
  echo -e "$report" > "$output_file"
  echo "Report written to: $output_file"
else
  echo -e "$report"
fi
