#!/usr/bin/env bash
# Collect agent-flow usage statistics
# Usage: bash agent-flow/scripts/evolution-stats.sh [--project-root <path>]
set -euo pipefail
project_root="${1:-.}"
af_dir="$project_root/agent-flow"
changes_dir="$af_dir/changes"
# Count changes
total_changes=0
completed_changes=0
ac_total=0
if [ -d "$changes_dir" ]; then
  for d in "$changes_dir"/*/; do
    [ "$(basename "$d")" = ".gitkeep" ] && continue
    [ ! -d "$d" ] && continue
    total_changes=$((total_changes + 1))
    [ -f "$d/REPORT.md" ] && completed_changes=$((completed_changes + 1))
    [ -f "$d/TASKS.md" ] && ac_total=$((ac_total + $(grep -c 'AC-[0-9]' "$d/TASKS.md" 2>/dev/null || echo 0)))
  done
fi
# Count knowledge files
k_count=0
[ -d "$af_dir/knowledge" ] && k_count=$(find "$af_dir/knowledge" -maxdepth 1 -type f ! -name '.gitkeep' 2>/dev/null | wc -l)
# Count ADRs
adr_count=0
[ -d "$af_dir/decisions" ] && adr_count=$(find "$af_dir/decisions" -name 'ADR-*' 2>/dev/null | wc -l)
cat << STATSEOF
# Evolution Stats

Generated: $(date '+%Y-%m-%d %H:%M')

## Project Activity

| Metric | Value |
|--------|-------|
| Total Changes | $total_changes |
| Completed | $completed_changes |
| Active | $((total_changes - completed_changes)) |
| Completion Rate | $( [ "$total_changes" -gt 0 ] && echo "$((completed_changes * 100 / total_changes))%" || echo "N/A" ) |

## Knowledge & Decisions

| Metric | Value |
|--------|-------|
| Knowledge Files | $k_count |
| ADRs | $adr_count |
| Total ACs | $ac_total |

---
*Generated by evolution-stats.sh*
STATSEOF
