<#
.SYNOPSIS
Collect agent-flow usage statistics for data-driven evolution.
.DESCRIPTION
Scans change directories, check results, and script run history to produce stats.
#>
param(
    [string]$ProjectRoot = "."
)
$ErrorActionPreference = "Stop"
$afDir = Join-Path $ProjectRoot "agent-flow"
$changesDir = Join-Path $afDir "changes"
$logsDir = Join-Path $afDir "logs"
$scriptsDir = Join-Path $afDir "scripts"
$stats = @{
    total_changes = 0
    completed_changes = 0
    active_changes = 0
    scripts_run = @{}
    total_scripts = 0
    ac_total = 0
    ac_pass = 0
    knowledge_files = @{}
    decision_count = 0
}
# Count changes
if (Test-Path $changesDir) {
    $changes = Get-ChildItem $changesDir -Directory | Where-Object { $_.Name -ne '.gitkeep' }
    $stats.total_changes = $changes.Count
    foreach ($c in $changes) {
        $verify = Join-Path $c.FullName "VERIFY.md"
        if (Test-Path $verify) { $stats.completed_changes++ } else { $stats.active_changes++ }
        # Count ACs
        $tasks = Join-Path $c.FullName "TASKS.md"
        if (Test-Path $tasks) {
            $t = Get-Content $tasks -Raw -Encoding utf8 -ErrorAction SilentlyContinue
            $acs = [regex]::Matches($t, 'AC-\d+')
            $stats.ac_total += $acs.Count
            foreach ($m in $acs) { if ($t -match "$($m.Value).*PASS|$($m.Value).*Done") { $stats.ac_pass++ } }
        }
    }
}
# Count scripts
if (Test-Path $scriptsDir) {
    $scripts = Get-ChildItem $scriptsDir -Filter "*.ps1" | Where-Object { $_.Name -notmatch '^_' }
    $stats.total_scripts = $scripts.Count
}
# Count knowledge
$knowledgeDir = Join-Path $afDir "knowledge"
if (Test-Path $knowledgeDir) {
    $kFiles = Get-ChildItem $knowledgeDir -File
    foreach ($f in $kFiles) {
        $content = Get-Content $f.FullName -Raw -Encoding utf8 -ErrorAction SilentlyContinue
        $lineCount = ($content -split "`n").Count
        $stats.knowledge_files[$f.Name] = @{ lines = $lineCount; path = $f.FullName }
    }
}
# Count decisions
$decisionsDir = Join-Path $afDir "decisions"
if (Test-Path $decisionsDir) {
    $stats.decision_count = (Get-ChildItem $decisionsDir -Filter "ADR-*").Count
}
# Output report
@"
# Evolution Stats

Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')

## Project Activity

| Metric | Value |
|--------|-------|
| Total Changes | $($stats.total_changes) |
| Completed | $($stats.completed_changes) |
| Active | $($stats.active_changes) |
| Completion Rate | $(if ($stats.total_changes -gt 0) { "$([math]::Round($stats.completed_changes/$stats.total_changes*100))%" } else { "N/A" }) |

## Code Quality

| Metric | Value |
|--------|-------|
| Total ACs | $($stats.ac_total) |
| AC Pass Rate | $(if ($stats.ac_total -gt 0) { "$([math]::Round($stats.ac_pass/$stats.ac_total*100))%" } else { "N/A" }) |
| Check Scripts | $($stats.total_scripts) |
| Decisions (ADRs) | $($stats.decision_count) |

## Knowledge Base

$(if ($stats.knowledge_files.Count -gt 0) {
    $stats.knowledge_files.GetEnumerator() | Sort-Object -Property Name | ForEach-Object {
        "| $($_.Key) | $($_.Value.lines) lines |"
    }
} else { "(No knowledge files yet)" })

---
*Generated by evolution-stats.ps1*
"@
