<#
.SYNOPSIS
Generate improvement suggestions based on evolution stats.
.DESCRIPTION
Analyzes project activity patterns and suggests concrete improvements.
#>
param(
    [string]$ProjectRoot = "."
)
$ErrorActionPreference = "Stop"
$afDir = Join-Path $ProjectRoot "agent-flow"
$changesDir = Join-Path $afDir "changes"
$suggestions = @()
# 1. Check change completion rate
$total = 0; $completed = 0
if (Test-Path $changesDir) {
    $dirs = Get-ChildItem $changesDir -Directory | Where-Object { $_.Name -ne '.gitkeep' }
    $total = $dirs.Count
    foreach ($d in $dirs) {
        if (Test-Path (Join-Path $d.FullName "REPORT.md")) { $completed++ }
    }
}
if ($total -gt 0) {
    $rate = $completed / $total
    if ($rate -lt 0.5) {
        $suggestions += @{ priority = "HIGH"; area = "Process"; suggestion = "Change completion rate is $([math]::Round($rate*100))%. Consider simplifying requirements or reducing scope per change." }
    } elseif ($rate -gt 0.9) {
        $suggestions += @{ priority = "LOW"; area = "Process"; suggestion = "High completion rate ($([math]::Round($rate*100))%). Process is well-calibrated." }
    }
}
# 2. Check knowledge utilization
$kDir = Join-Path $afDir "knowledge"
$kCount = 0
if (Test-Path $kDir) { $kCount = (Get-ChildItem $kDir -File | Where-Object { $_.Name -ne '.gitkeep' }).Count }
if ($kCount -eq 0 -and $total -gt 0) {
    $suggestions += @{ priority = "HIGH"; area = "Knowledge"; suggestion = "No knowledge files found after $total changes. Start recording pitfalls and module maps." }
} elseif ($kCount -lt 3 -and $total -gt 3) {
    $suggestions += @{ priority = "MEDIUM"; area = "Knowledge"; suggestion = "Only $kCount knowledge files for $total changes. Consider adding glossary.md and module-map.md." }
}
# 3. Check ADR usage
$dDir = Join-Path $afDir "decisions"
$adrCount = 0
if (Test-Path $dDir) { $adrCount = (Get-ChildItem $dDir -Filter "ADR-*").Count }
if ($adrCount -eq 0 -and $total -gt 2) {
    $suggestions += @{ priority = "MEDIUM"; area = "Decisions"; suggestion = "No ADRs recorded after $total changes. Record architecture decisions as they're made." }
}
# 4. Check if ECC is available
$hasEcc = Test-Path "$env:USERPROFILE\.pi\agent\npm\node_modules\ecc-universal"
$hasSkills = Test-Path "$env:USERPROFILE\.pi\agent\skills"
if (-not $hasEcc -and -not $hasSkills) {
    $suggestions += @{ priority = "MEDIUM"; area = "ECC"; suggestion = "ECC skills not installed. Run 'pi install npm:ecc-universal' or 'scripts/setup-new-pc.ps1' to enable skill acceleration." }
}
# 5. Check EVOLUTION.md quality
$evolutionDir = Join-Path $afDir "knowledge"
$hasImprovementTracker = Test-Path (Join-Path $evolutionDir "improvement-tracker.md")
if (-not $hasImprovementTracker -and $total -gt 2) {
    $suggestions += @{ priority = "LOW"; area = "Evolution"; suggestion = "Create improvement-tracker.md to track recurring process improvement suggestions." }
}
# Output
@"
# Evolution Suggestions

Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')

## Summary

| Metric | Value |
|--------|-------|
| Total Changes | $total |
| Completed | $completed |
| Knowledge Files | $kCount |
| ADRs | $adrCount |

## Improvement Suggestions

$(if ($suggestions.Count -eq 0) {
    "No suggestions at this time. Project is in good shape."
} else {
    $suggestions | Sort-Object { if ($_.priority -eq "HIGH") { 0 } elseif ($_.priority -eq "MEDIUM") { 1 } else { 2 } } | ForEach-Object {
        "- [$($_.priority)] [$($_.area)] $($_.suggestion)"
    }
})

---
*Generated by evolution-suggest.ps1 — run periodically to track project health*
"@
