#!/usr/bin/env bash
# Generate improvement suggestions based on project stats
# Usage: bash agent-flow/scripts/evolution-suggest.sh [--project-root <path>]
set -euo pipefail
project_root="${1:-.}"
af_dir="$project_root/agent-flow"
changes_dir="$af_dir/changes"
# Count changes and completion
total=0; completed=0
if [ -d "$changes_dir" ]; then
  for d in "$changes_dir"/*/; do
    [ "$(basename "$d")" = ".gitkeep" ] && continue
    [ ! -d "$d" ] && continue
    total=$((total + 1))
    [ -f "$d/REPORT.md" ] && completed=$((completed + 1))
  done
fi
# Count knowledge
k_count=0
[ -d "$af_dir/knowledge" ] && k_count=$(find "$af_dir/knowledge" -maxdepth 1 -type f ! -name '.gitkeep' 2>/dev/null | wc -l)
# Count ADRs
adr_count=0
[ -d "$af_dir/decisions" ] && adr_count=$(find "$af_dir/decisions" -name 'ADR-*' 2>/dev/null | wc -l)
# Build suggestions
suggestions=""
[ "$total" -gt 0 ] && [ "$completed" -eq 0 ] && suggestions="$suggestions\n- [HIGH] [Process] No completed changes yet. Start with a small task to validate the workflow."
[ "$k_count" -eq 0 ] && [ "$total" -gt 0 ] && suggestions="$suggestions\n- [HIGH] [Knowledge] No knowledge files found. Start documenting with glossary.md and pitfalls.md."
[ "$adr_count" -eq 0 ] && [ "$total" -gt 2 ] && suggestions="$suggestions\n- [MEDIUM] [Decisions] No ADRs recorded. Document architecture decisions as they're made."
[ "$total" -gt 3 ] && [ "$k_count" -lt 3 ] && suggestions="$suggestions\n- [MEDIUM] [Knowledge] Only $k_count knowledge files for $total changes. Consider adding module-map.md and verification.md."
[ -z "$suggestions" ] && suggestions="\nNo suggestions at this time. Project is in good shape."
cat << SUGGESTEOF
# Evolution Suggestions

Generated: $(date '+%Y-%m-%d %H:%M')

## Summary

| Metric | Value |
|--------|-------|
| Total Changes | $total |
| Completed | $completed |
| Knowledge Files | $k_count |
| ADRs | $adr_count |

## Improvement Suggestions
$suggestions

---
*Generated by evolution-suggest.sh*
SUGGESTEOF
