#!/usr/bin/env bash
# Auto-detect the appropriate flow level (Light/Standard/Heavy) for a change.
# Usage: bash agent-flow/scripts/flow-detect.sh --change-dir <path> [--strict]

set -euo pipefail

CHANGE_DIR=""
STRICT=false
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --change-dir) CHANGE_DIR="$2"; shift 2 ;;
    --strict) STRICT=true; shift ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

[ -n "$CHANGE_DIR" ] || { echo "Specify --change-dir <path>"; exit 1; }
[ -d "$CHANGE_DIR" ] || { echo "Directory not found: $CHANGE_DIR"; exit 1; }

# ── Read change text ──
CHANGE_FILE="$CHANGE_DIR/CHANGE.md"
CHANGE_TEXT=""
[ -f "$CHANGE_FILE" ] && CHANGE_TEXT="$(cat "$CHANGE_FILE")"

SCAN_FILE="$CHANGE_DIR/CODE_SCAN.md"
SCAN_TEXT=""
[ -f "$SCAN_FILE" ] && SCAN_TEXT="$(cat "$SCAN_FILE")"

TEXT="$CHANGE_TEXT $SCAN_TEXT"

# ── Risk factor detection ──
RISK_COUNT=0
MAX_SEVERITY=0
RISK_NAMES=""
LIGHT_SCORE=0
LIGHT_NAMES=""

# Heavy triggers
check_risk() {
  local name="$1" sev="$2" pattern="$3"
  if echo "$TEXT" | grep -Eqi "$pattern"; then
    RISK_COUNT=$((RISK_COUNT + 1))
    [ "$sev" -gt "$MAX_SEVERITY" ] && MAX_SEVERITY=$sev
    [ -n "$RISK_NAMES" ] && RISK_NAMES="$RISK_NAMES, "
    RISK_NAMES="$RISK_NAMES$name (sev=$sev)"
  fi
}

# Light indicators
check_light() {
  local name="$1" weight="$2" pattern="$3"
  if echo "$TEXT" | grep -Eqi "$pattern"; then
    LIGHT_SCORE=$((LIGHT_SCORE + weight))
    [ -n "$LIGHT_NAMES" ] && LIGHT_NAMES="$LIGHT_NAMES, "
    LIGHT_NAMES="$LIGHT_NAMES$name"
  fi
}

check_risk "new_module" 3 "新模块|new module|新包|new package"
check_risk "schema_change" 3 "schema|数据库|database|迁移|migration|DDL|ALTER TABLE|CREATE TABLE"
check_risk "auth_permission" 3 "权限|permission|auth|认证|角色|role|匿名|登录|token"
check_risk "public_api" 3 "API|接口|contract|契约|REST|endpoint|暴露"
check_risk "state_machine" 3 "状态机|state machine|工作流|workflow|状态流转"
check_risk "cache_token" 2 "缓存|cache|Redis|Token|令牌"
check_risk "websocket" 3 "WebSocket|websocket|实时|realtime|长连接|SSE"
check_risk "workflow" 3 "工作流|workflow|审批|approval|流转"
check_risk "deployment" 3 "部署|deploy|生产|production|配置"
check_risk "incident" 3 "P0|P1|生产事故|线上故障|数据丢失|data loss|安全漏洞"

check_light "文案修改" 1 "文案|文案修改|文字|copy|文本"
check_light "单文件修复" 1 "单文件|single file|bugfix|修复.*bug"
check_light "低风险样式" 1 "样式|样式调整|CSS|style|颜色|间距"
check_light "已有测试覆盖" 1 "已有测试|已有.*覆盖|测试.*已存在"

# ── Classify ──
SUGGESTED="Standard"
CONFIDENCE="medium"
REASONING=""

if [ "$RISK_COUNT" -ge 2 ] || [ "$MAX_SEVERITY" -ge 3 ] || [ "$STRICT" = true ]; then
  SUGGESTED="Heavy"
  CONFIDENCE="high"
  REASONING="High risk: $RISK_COUNT risk factors detected (max severity $MAX_SEVERITY)"
elif [ "$RISK_COUNT" -eq 1 ] && [ "$MAX_SEVERITY" -le 2 ]; then
  SUGGESTED="Standard"
  CONFIDENCE="medium"
  REASONING="Low risk factor: $RISK_NAMES"
elif [ "$LIGHT_SCORE" -ge 2 ]; then
  SUGGESTED="Light"
  CONFIDENCE="medium"
  REASONING="Light indicators: $LIGHT_NAMES"
elif [ "$RISK_COUNT" -eq 0 ] && [ "$LIGHT_SCORE" -eq 0 ]; then
  SUGGESTED="Standard"
  CONFIDENCE="low"
  REASONING="No clear indicators — defaulting to Standard"
else
  REASONING="Mixed signals — defaulting to $SUGGESTED"
fi

# ── Build report ──
REPORT="# Flow Level Detection

Change: $(basename "$CHANGE_DIR")
Generated: $(date '+%Y-%m-%d %H:%M')

## Classification

| Aspect | Value |
|--------|-------|
| **Suggested Flow** | **$SUGGESTED** |
| Confidence | $CONFIDENCE |
| Risk factors found | $RISK_COUNT |
| Light indicators | $LIGHT_SCORE |

"

if [ -n "$RISK_NAMES" ]; then
  REPORT="$REPORT
## Risk Factors Detected

$RISK_NAMES

"
fi

if [ -n "$LIGHT_NAMES" ]; then
  REPORT="$REPORT
## Light Indicators

$LIGHT_NAMES

"
fi

REPORT="$REPORT
## Reasoning

- $REASONING
"

if [ "$SUGGESTED" = "Heavy" ]; then
  REPORT="$REPORT

## Required for Heavy Flow

- [ ] PLAN.md — execution phases and gates
- [ ] Plan Audit (Verdict: accept)
- [ ] Closure Audit before marking done
- [ ] All 12 artifacts (incl. PLAN.md, AUDIT.md, REVIEW.md)
- [ ] TDD enforcement (RED→GREEN→REFACTOR per task)
"
fi

if [ "$CONFIDENCE" = "low" ]; then
  REPORT="$REPORT
## Notes

⚠️ Low confidence — review CHANGE.md to add more context about risk, scope, and impact.
"
fi

REPORT="$REPORT
---
*Generated by flow-detect.sh*
"

if [ -n "$OUTPUT" ]; then
  echo -e "$REPORT" > "$OUTPUT"
  echo "Report written to: $OUTPUT"
else
  echo -e "$REPORT"
fi
