#!/usr/bin/env bash
# Detect gate fatigue — gates that consistently pass without finding issues.
# Usage: bash agent-flow/scripts/gate-fatigue-check.sh [--threshold 5] [--output report.md]

set -euo pipefail

CHANGES_ROOT="agent-flow/changes"
THRESHOLD=5
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --changes-root) CHANGES_ROOT="$2"; shift 2 ;;
    --threshold) THRESHOLD="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CHANGES_DIR="$ROOT/$CHANGES_ROOT"

if [ ! -d "$CHANGES_DIR" ]; then
  echo "No changes directory found at $CHANGES_DIR"
  exit 0
fi

# ── Collect gate data ──
declare -A GATE_TOTAL GATE_PASS GATE_FAIL GATE_CONSEC GATE_LAST
CHANGE_COUNT=0

for change_dir in "$CHANGES_DIR"/*/; do
  [ ! -d "$change_dir" ] && continue
  CHECK_JSON="$change_dir/CHECK_RESULT.json"
  [ ! -f "$CHECK_JSON" ] && continue

  CHANGE_COUNT=$((CHANGE_COUNT + 1))

  # Extract gate names and results from JSON
  while IFS='|' read -r gate_name gate_result; do
    [ -z "$gate_name" ] && continue
    GATE_TOTAL["$gate_name"]=$((GATE_TOTAL["$gate_name"] + 1))

    if [ "$gate_result" = "pass" ]; then
      GATE_PASS["$gate_name"]=$((GATE_PASS["$gate_name"] + 1))
      if [ "${GATE_LAST["$gate_name"]:-}" = "pass" ]; then
        GATE_CONSEC["$gate_name"]=$((GATE_CONSEC["$gate_name"] + 1))
      else
        GATE_CONSEC["$gate_name"]=1
      fi
    else
      GATE_FAIL["$gate_name"]=$((GATE_FAIL["$gate_name"] + 1))
      GATE_CONSEC["$gate_name"]=0
    fi
    GATE_LAST["$gate_name"]="$gate_result"
  done < <(python3 -c "
import json,sys
try:
  with open('$CHECK_JSON') as f:
    data = json.load(f)
  for g,r in data.get('gates',{}).items():
    print(f\"{g}|{r.get('result','unknown')}\")
except: pass
" 2>/dev/null || true)
done

# ── Build report ──
FATIGUE_COUNT=0
HEALTHY_COUNT=0
BELOW_COUNT=0
FATIGUE_ROWS=""
HEALTHY_ROWS=""
BELOW_ROWS=""

for g in "${!GATE_TOTAL[@]}"; do
  total="${GATE_TOTAL[$g]}"
  pass="${GATE_PASS[$g]:-0}"
  fail="${GATE_FAIL[$g]:-0}"
  consec="${GATE_CONSEC[$g]:-0}"

  if [ "$consec" -ge "$THRESHOLD" ] && [ "$fail" -eq 0 ]; then
    FATIGUE_COUNT=$((FATIGUE_COUNT + 1))
    FATIGUE_ROWS="$FATIGUE_ROWS| $g | $consec | $total | $pass |\n"
  elif [ "$fail" -gt 0 ]; then
    HEALTHY_COUNT=$((HEALTHY_COUNT + 1))
    HEALTHY_ROWS="$HEALTHY_ROWS| $g | $total | $pass | $fail |\n"
  else
    BELOW_COUNT=$((BELOW_COUNT + 1))
    BELOW_ROWS="$BELOW_ROWS| $g | $consec | $total |\n"
  fi
done

REPORT="# Gate Fatigue Report

Generated: $(date '+%Y-%m-%d %H:%M')
Threshold: $THRESHOLD consecutive passes without failure
Changes scanned: $CHANGE_COUNT
Gates analyzed: ${#GATE_TOTAL[@]}

"

if [ "$FATIGUE_COUNT" -gt 0 ]; then
  REPORT="$REPORT
## ⚠️ Fatigued Gates (No failures detected)

These gates have passed $THRESHOLD+ times without detecting any issue.
Consider: reviewing whether they still add value, or downgrading for low-risk changes.

| Gate | Consecutive Passes | Total Runs | Total Passes |
|------|-------------------|------------|--------------|
$(echo -e "$FATIGUE_ROWS")
"
else
  REPORT="$REPORT
## ✅ No Fatigued Gates

All gates have detected at least one issue, or have not yet reached the threshold.

"
fi

if [ "$HEALTHY_COUNT" -gt 0 ]; then
  REPORT="$REPORT
## ✅ Healthy Gates (Have detected failures)

| Gate | Total Runs | Passes | Failures |
|------|------------|--------|----------|
$(echo -e "$HEALTHY_ROWS")
"
fi

if [ "$BELOW_COUNT" -gt 0 ]; then
  REPORT="$REPORT
## 🔍 Gates Below Fatigue Threshold

| Gate | Consecutive Passes | Total Runs |
|------|-------------------|------------|
$(echo -e "$BELOW_ROWS")
"
fi

REPORT="$REPORT
## Summary Statistics

- Total gates tracked: ${#GATE_TOTAL[@]}
- Fatigued gates: $FATIGUE_COUNT
- Healthy gates (detected failures): $HEALTHY_COUNT
- Gates below threshold: $BELOW_COUNT
- Changes with CHECK_RESULT.json: $CHANGE_COUNT

---
*Generated by gate-fatigue-check.sh*
"

if [ -n "$OUTPUT" ]; then
  echo -e "$REPORT" > "$OUTPUT"
  echo "Report written to: $OUTPUT"
else
  echo -e "$REPORT"
fi
