<#
.SYNOPSIS
Auto-generate VERIFY.md by collecting AC evidence and check outputs.
.DESCRIPTION
Reads TASKS.md ACs, runs verification commands, and generates VERIFY.md with evidence.
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$ChangeDir,
    [string]$ProjectRoot = "."
)
$ErrorActionPreference = "Stop"
$verifyOut = Join-Path $ChangeDir "VERIFY.md"
if (Test-Path $verifyOut) {
    Write-Host "VERIFY.md already exists. Edit manually or delete to regenerate." -ForegroundColor Yellow
    exit 0
}

# --- Collect ACs from TASKS.md ---
$tasksMd = Join-Path $ChangeDir "TASKS.md"
$acs = @()
$acMap = @{}
if (Test-Path $tasksMd) {
    $tasks = Get-Content $tasksMd -Raw -Encoding utf8 -ErrorAction SilentlyContinue
    $acMatches = [regex]::Matches($tasks, '(AC-\d+)')
    $acs = $acMatches.Value | Sort-Object -Unique
    foreach ($m in $acMatches) {
        # Try to find a description after the AC
        $lines = $tasks -split "`n"
        for ($i = 0; $i -lt $lines.Count; $i++) {
            if ($lines[$i] -match $m.Value) {
                $descLine = $lines[$i]
                # Get next non-empty line if this is just "| AC-XX |"
                if ($descLine -match '^\s*\|?\s*AC-\d+\s*\|?\s*$') {
                    for ($j = $i + 1; $j -lt $lines.Count -and $j -lt $i + 5; $j++) {
                        if (-not [string]::IsNullOrWhiteSpace($lines[$j]) -and $lines[$j] -notmatch '^\s*\|?\s*[-]+\s*\|') {
                            $descLine = $lines[$j]; break
                        }
                    }
                }
                $acMap[$m.Value] = $descLine.Trim().Trim('|').Trim()
                break
            }
        }
    }
}
if ($acs.Count -eq 0) {
    Write-Host "No ACs found in TASKS.md. Creating basic VERIFY.md template." -ForegroundColor Yellow
    $acs = @("AC-01", "AC-02", "AC-03")
}

# --- Run common verification commands ---
Write-Host "Running verification commands..." -ForegroundColor Cyan
$results = @{}
$hasNode = Test-Path (Join-Path $ProjectRoot "package.json")
$hasTsc = Test-Path (Join-Path $ProjectRoot "tsconfig.json")

# TypeScript check
if ($hasTsc) {
    Write-Host "  Running TypeScript check..." -ForegroundColor Gray
    $tsOut = & npx tsc --noEmit 2>&1 | Out-String
    $tsPass = $LASTEXITCODE -eq 0
    $results["TypeScript Check"] = if ($tsPass) { "PASS" } else { "FAIL ($($tsOut.Trim() -split "`n" | Select-Object -First 3))" }
}
# Lint check
if ($hasNode) {
    $lintCmds = @("npx eslint . 2>&1", "npx biome check . 2>&1")
    foreach ($cmd in $lintCmds) {
        $lintOut = Invoke-Expression $cmd 2>&1 | Out-String
        if ($LASTEXITCODE -eq 0 -or $LASTEXITCODE -eq 1) {
            $results["Lint Check"] = if ($LASTEXITCODE -eq 0) { "PASS" } else { "WARN ($($lintOut.Trim() -split "`n" | Select-Object -First 2))" }
            break
        }
    }
    if (-not $results.ContainsKey("Lint Check")) { $results["Lint Check"] = "SKIP (no linter configured)" }
}
# Test check
if ($hasNode) {
    $testOut = & npm test 2>&1 | Out-String
    $results["Tests"] = if ($LASTEXITCODE -eq 0) { "PASS" } else { "FAIL or no tests configured" }
}
# Security scan (basic)
if ($hasNode) {
    $secOut = & npx npm audit --audit-level=high 2>&1 | Out-String
    $results["Security Audit"] = if ($LASTEXITCODE -eq 0) { "PASS" } else { "WARN (vulnerabilities found)" }
}
# Secrets scan
$secretOut = ""
if ($hasNode) {
    $secretOut = & grep -r 'sk-[A-Za-z0-9]\{20,\}\|ghp_[A-Za-z0-9]\{36,\}' --include="*.{ts,js,py,go,rs}" $ProjectRoot 2>&1 | Out-String
} else {
    $secretOut = & Select-String -Path "$ProjectRoot\*" -Pattern 'sk-[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{36,}' -ErrorAction SilentlyContinue | Out-String
}
$results["Secrets Check"] = if ([string]::IsNullOrWhiteSpace($secretOut)) { "PASS (no secrets found)" } else { "FAIL (secrets detected!)" }

# --- Generate VERIFY.md ---
@"
# VERIFY

## AC Evidence

| AC | Requirement | Evidence Type | Evidence Location | Result | Residual Risk |
|----|-------------|---------------|-------------------|--------|---------------|
$(foreach ($ac in $acs) {
    $desc = if ($acMap.ContainsKey($ac)) { $acMap[$ac] } else { $ac }
    "| $ac | $desc | (manual) | (file:line) | (PASS/FAIL) | (none) |`n"
})

## Verification Results

| Check | Status |
|-------|--------|
$(foreach ($k in $results.Keys) { "| $k | $($results[$k]) |`n" })

## Manual Verification

- [ ] Code review completed $(if ($hasNode) { "(/ecc-review)" })
- [ ] Security review completed $(if ($hasNode) { "(/ecc-security)" })
- [ ] All ACs pass with evidence
- [ ] No undeclared files modified
- [ ] Edge cases tested
- [ ] Error handling verified

## Definition of Done

All ACs have evidence of passing. No CRITICAL or HIGH issues open.

---
*Generated by generate-verify.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')*
*Edit to add manual verification results.*
"@ | Set-Content $verifyOut -Encoding utf8
Write-Host "VERIFY.md generated: $verifyOut" -ForegroundColor Green
Write-Host "  ACs: $($acs.Count)"
Write-Host "  Auto-checks: $($results.Count)"
Write-Host "  Next: run manual verifications and edit evidence cells"
