#!/usr/bin/env bash
# Auto-generate CODE_SCAN.md by detecting project type and running scans
# Usage: bash agent-flow/scripts/generate-scan.sh --change-dir <path> [--project-root <path>]
set -euo pipefail
change_dir=""
project_root="."
while [ "$#" -gt 0 ]; do
  case "$1" in
    --change-dir|-ChangeDir) change_dir="$2"; shift 2 ;;
    --project-root|-ProjectRoot) project_root="$2"; shift 2 ;;
    *) echo "Unknown: $1"; exit 2 ;;
  esac
done
[ -z "$change_dir" ] && { echo "Error: --change-dir required"; exit 1; }
scan_out="$change_dir/CODE_SCAN.md"
[ -f "$scan_out" ] && { echo "CODE_SCAN.md already exists"; exit 0; }
# Detect stack
stack=""
[ -f "$project_root/package.json" ] && stack="Node.js"
[ -f "$project_root/pom.xml" ] && stack="${stack:+$stack }Java"
[ -f "$project_root/Cargo.toml" ] && stack="${stack:+$stack }Rust"
[ -f "$project_root/go.mod" ] && stack="${stack:+$stack }Go"
[ -f "$project_root/pyproject.toml" ] && stack="${stack:+$stack }Python"
[ -f "$project_root/requirements.txt" ] && stack="${stack:+$stack }Python"
[ -z "$stack" ] && stack="unknown"
# Build files
build_files=""
for f in package.json pom.xml build.gradle Cargo.toml go.mod pyproject.toml requirements.txt Dockerfile compose.yml; do
  [ -f "$project_root/$f" ] && build_files="${build_files:+$build_files, }$f"
done
[ -z "$build_files" ] && build_files="(none detected)"
# Source dirs
src_dirs=""
for d in src app server client lib cmd pkg internal core api web frontend backend services components; do
  [ -d "$project_root/$d" ] && src_dirs="${src_dirs:+$src_dirs, }$d"
done
[ -z "$src_dirs" ] && src_dirs="(none detected)"
# Extract goal from STATE.md
goal="New feature/module"
state_file="$change_dir/STATE.md"
[ -f "$state_file" ] && goal=$(grep -i "goal:" "$state_file" 2>/dev/null | head -1 | sed 's/.*goal://i' | sed 's/^[[:space:]]*//')
[ -z "$goal" ] && goal="New feature/module"
cat > "$scan_out" << SCANEOF
# CODE_SCAN

## Project Overview

| Field | Value |
|-------|-------|
| **Tech Stack** | $stack |
| **Build Files** | $build_files |
| **Source Dirs** | $src_dirs |
| **Change Scope** | $goal |

## Code-First Findings

### 1. Similar Implementations

> Search project for similar features/modules. Look for naming patterns.

Search: find "$project_root" -name '*service*' -not -path '*/node_modules/*' -not -path '*/.git/*' 2>/dev/null | head -10

### 2. Reusable Abstractions

- (list existing utilities, base classes, common patterns found)

### 3. Database Schema / Migrations

$([ -d "$project_root/migrations" -o -d "$project_root/prisma" ] && echo "- Migration directory found. Review existing schema." || echo "- (no migration directory detected)")

### 4. API Routes / Endpoints

- (scan for route definitions, controllers, or API declarations)

### 5. Permission / Auth Models

- (check for auth middleware, permission annotations, config)

### 6. Test Patterns

- (review existing tests for style and coverage expectations)

## Protected Areas Check

- [ ] Database schema change?
- [ ] Auth/permission change?
- [ ] Public API contract change?
- [ ] Deployment/production config change?
- [ ] Destructive data operation?

## Scan Notes

- Stack auto-detected: $stack
- $(date '+%Y-%m-%d %H:%M')
- Use @ecc-explorer for deeper codebase reconnaissance

---
*Generated by generate-scan.sh — edit to add actual findings*
SCANEOF
echo "CODE_SCAN.md generated: $scan_out"
echo "Stack: $stack"
echo "Next: edit CODE_SCAN.md with actual findings, then run scan-check"
