#!/usr/bin/env bash
# Generate AUDIT.md by pre-filling checklists from existing change artifacts
# Usage: bash agent-flow/scripts/generate-audit.sh --change-dir <path>
set -euo pipefail
change_dir=""
while [ "$#" -gt 0 ]; do
  case "$1" in --change-dir|-ChangeDir) change_dir="$2"; shift 2 ;; *) echo "Unknown: $1"; exit 2 ;; esac
done
[ -z "$change_dir" ] && { echo "Error: --change-dir required"; exit 1; }
audit_out="$change_dir/AUDIT.md"
[ -f "$audit_out" ] && { echo "AUDIT.md already exists"; exit 0; }
# Count existing artifacts
plan_ready=0; design_ready=0; tasks_ready=0; codescan_ready=0; verify_ready=0; evolution_ready=0
[ -f "$change_dir/PLAN.md" ] && plan_ready=1
[ -f "$change_dir/DESIGN.md" ] && design_ready=1
[ -f "$change_dir/TASKS.md" ] && tasks_ready=1
[ -f "$change_dir/CODE_SCAN.md" ] && codescan_ready=1
[ -f "$change_dir/VERIFY.md" ] && verify_ready=1
[ -f "$change_dir/EVOLUTION.md" ] && evolution_ready=1
plan_pass=$((codescan_ready + design_ready + tasks_ready + plan_ready))
closure_pass=$((verify_ready + evolution_ready))
cat > "$audit_out" << AUDITEOF
# AUDIT

> Generated from existing artifacts. Edit verdicts and add manual findings.

## Plan Audit

**Verdict**: pending

**Reviewer**: (assign)

**Date**: $(date '+%Y-%m-%d')

### Checklist

$([ $codescan_ready -eq 1 ] && echo "[x]" || echo "[ ]") Current baseline checked against live code
$([ $design_ready -eq 1 ] && echo "[x]" || echo "[ ]") Goals and Non-Goals clear
$([ $codescan_ready -eq 1 ] && echo "[x]" || echo "[ ]") Code scan lists similar implementations
$([ $design_ready -eq 1 ] && echo "[x]" || echo "[ ]") Protected areas identified
$([ $tasks_ready -eq 1 ] && echo "[x]" || echo "[ ]") read_files and write_files are bounded
$([ $plan_ready -eq 1 ] && echo "[x]" || echo "[ ]") Execution phases have exit criteria
$([ $verify_ready -eq 1 -o $tasks_ready -eq 1 ] && echo "[x]" || echo "[ ]") Closure gates are verifiable
$([ $design_ready -eq 1 ] && echo "[x]" || echo "[ ]") Risks have mitigations
[ ] Skill/tool choices are recorded

### Findings

(Add manual findings here)

---

## Closure Audit

**Verdict**: pending

**Reviewer**: (assign)

**Date**: $(date '+%Y-%m-%d')

### Checklist

$([ $verify_ready -eq 1 ] && echo "[x]" || echo "[ ]") Closure gates passed
$([ $verify_ready -eq 1 ] && echo "[x]" || echo "[ ]") Verification evidence recorded
$([ $verify_ready -eq 1 ] && echo "[x]" || echo "[ ]") AC coverage has evidence
$([ $codescan_ready -eq 1 ] && echo "[x]" || echo "[ ]") scan-check completed
$([ $design_ready -eq 1 ] && echo "[x]" || echo "[ ]") design-check completed
$([ $design_ready -eq 1 ] && echo "[x]" || echo "[ ]") alignment-check completed
$([ $tasks_ready -eq 1 ] && echo "[x]" || echo "[ ]") task-check completed
[ ] Drift checks completed
[ ] No undeclared files modified
[ ] task-boundary-check completed
[ ] manifest-check completed
$([ $evolution_ready -eq 1 ] && echo "[x]" || echo "[ ]") evolution-check completed
$([ $evolution_ready -eq 1 ] && echo "[x]" || echo "[ ]") Knowledge/decision/log/baseline updated

### Findings

(Add manual findings here)

---
*Generated by generate-audit.sh on $(date '+%Y-%m-%d %H:%M')*
*Edit verdicts, add reviewer, and fill manual findings.*
AUDITEOF
echo "AUDIT.md generated: $audit_out"
echo "Plan Audit: $plan_pass/9 items auto-verified"
echo "Closure Audit: $closure_pass/12 items auto-verified"
