<#
.SYNOPSIS
Generate AUDIT.md by pre-filling checklists from existing change artifacts.
.DESCRIPTION
Reads DESIGN.md, TASKS.md, PLAN.md and auto-populates the Plan Audit and Closure Audit checklists.
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$ChangeDir
)
$ErrorActionPreference = "Stop"
$auditOut = Join-Path $ChangeDir "AUDIT.md"
if (Test-Path $auditOut) {
    Write-Host "AUDIT.md already exists. Edit manually." -ForegroundColor Yellow
    exit 0
}
# Helper: check if a file exists and has meaningful content
function Test-FileReady($path) {
    if (-not (Test-Path $path)) { return $false }
    $c = Get-Content $path -Raw -Encoding utf8 -ErrorAction SilentlyContinue
    if ([string]::IsNullOrWhiteSpace($c)) { return $false }
    if ($c -match "(?i)(TODO|pending|fill this|not filled|template)") { return $false }
    return $true
}
$changeDir = $ChangeDir
$plan = Join-Path $changeDir "PLAN.md"
$design = Join-Path $changeDir "DESIGN.md"
$tasks = Join-Path $changeDir "TASKS.md"
$codeScan = Join-Path $changeDir "CODE_SCAN.md"
$verify = Join-Path $changeDir "VERIFY.md"
$checkResult = Join-Path $changeDir "CHECK_RESULT.json"
$review = Join-Path $changeDir "REVIEW.md"

# Auto-fill Plan Audit checklist
$planChecks = @(
    @{item="Current baseline checked against live code"; found = (Test-FileReady $codeScan)}
    @{item="Goals and Non-Goals clear"; found = (Test-FileReady $design) -or (Test-FileReady $plan)}
    @{item="Code scan lists similar implementations and reusable abstractions"; found = (Test-FileReady $codeScan)}
    @{item="Protected areas identified"; found = (Test-Path (Join-Path $changeDir "DESIGN.md"))}
    @{item="read_files and write_files are bounded"; found = (Test-FileReady $tasks)}
    @{item="Execution phases have exit criteria"; found = (Test-FileReady $plan) -or (Test-FileReady $tasks)}
    @{item="Closure gates are verifiable"; found = (Test-FileReady $verify) -or (Test-FileReady $tasks)}
    @{item="Risks have mitigations"; found = (Test-FileReady $design)}
    @{item="Skill/tool choices are recorded or explicitly none"; found = $true}
)

# Auto-fill Closure Audit checklist
$closureChecks = @(
    @{item="Closure gates passed"; found = (Test-FileReady $verify)}
    @{item="Verification evidence recorded"; found = (Test-FileReady $verify)}
    @{item="AC coverage has evidence"; found = (Test-FileReady $verify) -and (Select-String -Path $verify -Pattern "PASS" -ErrorAction SilentlyContinue -Quiet)}
    @{item="scan-check completed"; found = (Test-Path (Join-Path $changeDir "CODE_SCAN.md"))}
    @{item="design-check completed"; found = (Test-FileReady $design)}
    @{item="alignment-check completed"; found = (Test-FileReady $design) -and (Select-String -Path $design -Pattern "aligned" -ErrorAction SilentlyContinue -Quiet)}
    @{item="task-check completed"; found = (Test-FileReady $tasks)}
    @{item="Drift checks completed"; found = $false}
    @{item="No undeclared files modified"; found = $false}
    @{item="task-boundary-check completed"; found = $false}
    @{item="manifest-check completed"; found = $false}
    @{item="evolution-check completed"; found = (Test-Path (Join-Path $changeDir "EVOLUTION.md"))}
    @{item="Knowledge/decision/log/baseline updated"; found = (Test-Path (Join-Path $changeDir "EVOLUTION.md"))}
)

$planPass = ($planChecks | Where-Object { $_.found }).Count
$closurePass = ($closureChecks | Where-Object { $_.found }).Count

@"
# AUDIT

> Generated from existing artifacts. Edit verdicts and add manual findings.

## Plan Audit

**Verdict**: `pending` (auto-suggest: $(if ($planPass -ge 6) { "conditional" } else { "pending more evidence" }))

**Reviewer**: (assign)

**Date**: $(Get-Date -Format 'yyyy-MM-dd')

### Checklist ($planPass/$($planChecks.Count) auto-verified)

$(foreach ($c in $planChecks) { "[$(@{ $true = "x"; $false = " " }[$c.found])] $($c.item)" + "`n" })

### Findings

(Add manual findings here)

---

## Closure Audit

**Verdict**: `pending`

**Reviewer**: (assign)

**Date**: $(Get-Date -Format 'yyyy-MM-dd')

### Checklist ($closurePass/$($closureChecks.Count) auto-verified)

$(foreach ($c in $closureChecks) { "[$(@{ $true = "x"; $false = " " }[$c.found])] $($c.item)" + "`n" })

### Findings

(Add manual findings here)

---
*Generated by generate-audit.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')*
*Auto-filled $($planChecks.Count) Plan Audit + $($closureChecks.Count) Closure Audit items.*
*Edit verdicts, add reviewer, and fill manual findings.*
"@ | Set-Content $auditOut -Encoding utf8
Write-Host "AUDIT.md generated: $auditOut" -ForegroundColor Green
Write-Host "  Plan Audit: $planPass/$($planChecks.Count) items auto-verified"
Write-Host "  Closure Audit: $closurePass/$($closureChecks.Count) items auto-verified"
Write-Host "  Next: edit AUDIT.md — assign reviewer, fill findings, set verdict"
