<#
.SYNOPSIS
Generate TASKS.md from DESIGN.md for a change.
.DESCRIPTION
Reads DESIGN.md and generates a structured TASKS.md with tasks tied to ACs.
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$ChangeDir
)
$ErrorActionPreference = "Stop"
$design = Join-Path $ChangeDir "DESIGN.md"
$tasksOut = Join-Path $ChangeDir "TASKS.md"
if (-not (Test-Path $design)) { Write-Host "ERROR: DESIGN.md not found"; exit 1 }
if (Test-Path $tasksOut) { Write-Host "TASKS.md already exists. Edit manually."; exit 0 }
$reqMd = Join-Path $ChangeDir "REQUIREMENT.md"
$acs = @("AC-01", "AC-02", "AC-03")
if (Test-Path $reqMd) {
    $req = Get-Content $reqMd -Raw -Encoding utf8 -ErrorAction SilentlyContinue
    $found = [regex]::Matches($req, 'AC-\d+')
    if ($found.Count -gt 0) { $acs = $found.Value }
}

$taskSections = @()
for ($i = 0; $i -lt $acs.Count; $i++) {
    $taskNumber = $i + 1
    $title = if ($i -eq 0) { "Foundation/Setup" } elseif ($i -eq $acs.Count - 1) { "Verification & Report" } else { "Core Logic Step $i" }
    $priority = if ($i -eq 0) { "P0" } else { "P$($i.ToString())" }
    $taskSections += @"
### Task ${taskNumber}: $title

| Field | Value |
|-------|-------|
| **Status** | pending |
| **AC** | $($acs[$i]) |
| **Priority** | $priority |
| **Estimate** | (minutes) |

**read_files**:
- (list files to read before implementing)

**write_files**:
- (list files to create/modify)

**Implementation Notes**:
- (specific guidance)

**Verification Command**:
- (command to verify this task)

**Definition of Done**:
- [ ] All ACs pass
- [ ] Tests written and passing
- [ ] No lint/type errors
- [ ] Code reviewed
"@
}

$mappingRows = @()
for ($i = 0; $i -lt $acs.Count; $i++) {
    $mappingRows += "| $($acs[$i]) | Task $($i + 1) | (verification command) |"
}

$content = @"
# TASKS

> Generated from DESIGN.md. Edit to match actual implementation steps.

## Task List

$($taskSections -join "`n`n")

## AC-Task Mapping

| AC | Task | Verification |
|----|------|-------------|
$($mappingRows -join "`n")

---
*Generated by generate-tasks.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')*
"@

$content | Set-Content $tasksOut -Encoding utf8
Write-Host "TASKS.md generated: $tasksOut"
