#!/usr/bin/env bash
# Generate DESIGN.md skeleton from CODE_SCAN.md and project files.
# Usage: bash agent-flow/scripts/generate-design.sh --change-dir <path> [--project-root <path>]
set -euo pipefail
change_dir=""
project_root="."
while [ "$#" -gt 0 ]; do
  case "$1" in
    --change-dir|-ChangeDir) change_dir="$2"; shift 2 ;;
    --project-root|-ProjectRoot) project_root="$2"; shift 2 ;;
    *) echo "Unknown: $1"; exit 2 ;;
  esac
done
if [ -z "$change_dir" ]; then echo "Error: --change-dir required"; exit 1; fi
code_scan="$change_dir/CODE_SCAN.md"
design_out="$change_dir/DESIGN.md"
if [ ! -f "$code_scan" ]; then
  echo "ERROR: CODE_SCAN.md not found at $code_scan"
  echo "Run code-first scan first (use /af-scan or @ecc-explorer)"
  exit 1
fi
if [ -f "$design_out" ]; then
  echo "DESIGN.md already exists. Edit manually." >&2
  exit 0
fi
# Detect tech stack
tech=""
[ -f "$project_root/package.json" ] && tech="Node.js"
[ -f "$project_root/pom.xml" ] && tech="Java"
[ -f "$project_root/Cargo.toml" ] && tech="Rust"
[ -f "$project_root/go.mod" ] && tech="Go"
[ -f "$project_root/pyproject.toml" ] && tech="Python"
# Extract change description from STATE.md
desc="New feature/module"
state_md="$change_dir/STATE.md"
if [ -f "$state_md" ]; then
  extracted=$(grep -i "goal:" "$state_md" 2>/dev/null | head -1 | sed 's/.*goal://i' | sed 's/^[[:space:]]*//')
  [ -n "$extracted" ] && desc="$extracted"
fi
cat > "$design_out" << DESIGNEOF
# DESIGN

## 1. Module Boundary

**Scope**: $desc

**Tech Stack Detected**: ${tech:-unknown}

**Affected Modules**: (extract from CODE_SCAN.md)

**External Dependencies**: (list new deps)

## 2. API & Permissions

**REST Paths**: (design endpoints)

**HTTP Methods**: (GET/POST/PUT/DELETE)

**Permission Codes**: (if any)

**Anonymous Access**: (yes/no, default no)

## 3. Data Model

**New Tables/Collections**: (name and fields)

**Indexes**: (index fields)

**Migration Strategy**: (new migration / direct alter)

## 4. State Machine

> Write "N/A" if not applicable

## 5. Service Orchestration

**Call Chain**: (Controller -> Service -> Repository)

**Reusable Services**: (check CODE_SCAN.md findings)

## 6. Error Handling

**Error Types**: (business/system/validation)

**Error Codes**: (if project has conventions)

## 7. Idempotency, Rate Limiting, Audit

**Idempotency**: (for write operations)

**Rate Limiting**: (for public endpoints)

**Audit Log**: (for sensitive operations)

## 8. Test Strategy

**Unit Tests**: (core logic)

**Integration Tests**: (API endpoints)

**E2E Tests**: (user flows)

## 9. Deployment & Rollback

**Deployment Steps**:

**Rollback Plan**:

## 10. Security Design

- [ ] Input validation (length, type, range)
- [ ] Permission check
- [ ] SQL injection protection (parameterized queries)
- [ ] XSS protection (output encoding)
- [ ] Secrets management (no hardcoded keys)
- [ ] Dependency security (npm audit / equivalent)

## Design Alignment / Grill

Alignment Source: pending

Open Questions: pending

| # | Question | Confirmation (`user-confirmed` / `code-confirmed` / `pending`) | Evidence |
|------|---------|---------|------|
| 1 | Intent Risk | | pending | |
| 2 | Existing Code Fit | | pending | |
| 3 | Unnecessary Abstraction | | pending | |
| 4 | Protected Areas | | pending | |
| 5 | Boundary And Failure Modes | | pending | |

Alignment Verdict: pending

Skip Reason:

---
*Generated by agent-flow generate-design.sh on $(date '+%Y-%m-%d %H:%M')*
*Edit this file to reflect actual design decisions.*
DESIGNEOF
echo "DESIGN.md skeleton generated: $design_out"
echo "Next: edit DESIGN.md, then run design-check"
