#!/usr/bin/env bash
# Generate REPORT.md from change artifacts
# Usage: bash agent-flow/scripts/generate-report.sh --change-dir <path>
set -euo pipefail
change_dir=""
while [ "$#" -gt 0 ]; do
  case "$1" in --change-dir|-ChangeDir) change_dir="$2"; shift 2 ;; *) echo "Unknown: $1"; exit 2 ;; esac
done
[ -z "$change_dir" ] && { echo "Error: --change-dir required"; exit 1; }
report="$change_dir/REPORT.md"
[ -f "$report" ] && { echo "REPORT.md already exists"; exit 0; }
# Extract description
desc="Unnamed change"
change_file="$change_dir/CHANGE.md"
[ -f "$change_file" ] && desc=$(grep -i "description:" "$change_file" 2>/dev/null | head -1 | sed 's/.*description://i' | sed 's/^[[:space:]]*//')
[ -z "$desc" ] && desc="Unnamed change"
# Count ACs from TASKS.md
ac_total=0
tasks_file="$change_dir/TASKS.md"
[ -f "$tasks_file" ] && ac_total=$(grep -c 'AC-[0-9]' "$tasks_file" 2>/dev/null || echo 0)
cat > "$report" << REPORTEOF
# REPORT

## Change Summary

| Field | Value |
|-------|-------|
| **Description** | $desc |
| **Change Dir** | $change_dir |
| **Date** | $(date '+%Y-%m-%d %H:%M') |

## AC Coverage

| Metric | Count |
|--------|-------|
| Total ACs | $ac_total |
| Passed | (fill) |
| Coverage | (fill) |

## Check Results

| Check | Status |
|-------|--------|
| scan-check | (pending) |
| design-check | (pending) |
| alignment-check | (pending) |
| task-check | (pending) |
| code-drift-check | (pending) |
| blocked-check | (pending) |
| task-boundary-check | (pending) |
| manifest-check | (pending) |
| evolution-check | (pending) |
| check-change | (pending) |

## Verification Summary

(Fill in verification results here)

## Files Changed

(Fill in file list here)

## Lessons Learned

(What went well, what could be improved)

---
*Generated by generate-report.sh — edit to fill results*
REPORTEOF
echo "REPORT.md generated: $report"
