<#
.SYNOPSIS
Generate DESIGN.md skeleton from CODE_SCAN.md and project files.
.DESCRIPTION
Reads the existing CODE_SCAN.md from a change directory and project files,
then generates a structured DESIGN.md with all required sections filled.
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$ChangeDir,
    [string]$ProjectRoot = "."
)
$ErrorActionPreference = "Stop"
$codeScan = Join-Path $ChangeDir "CODE_SCAN.md"
$designOut = Join-Path $ChangeDir "DESIGN.md"
if (-not (Test-Path $codeScan)) {
    Write-Host "ERROR: CODE_SCAN.md not found at $codeScan" -ForegroundColor Red
    Write-Host "Run code-first scan first (use /af-scan or @ecc-explorer)"
    exit 1
}
if (Test-Path $designOut) {
    Write-Host "DESIGN.md already exists. Use -Force to overwrite or edit manually." -ForegroundColor Yellow
    exit 0
}
# Detect project tech stack
$techStack = @{}
if (Test-Path (Join-Path $ProjectRoot "package.json")) { $techStack["js"] = $true }
if (Test-Path (Join-Path $ProjectRoot "pom.xml")) { $techStack["java"] = $true }
if (Test-Path (Join-Path $ProjectRoot "Cargo.toml")) { $techStack["rust"] = $true }
if (Test-Path (Join-Path $ProjectRoot "go.mod")) { $techStack["go"] = $true }
if (Test-Path (Join-Path $ProjectRoot "pyproject.toml")) { $techStack["python"] = $true }
# Read CODE_SCAN summary to understand scope
$scanContent = Get-Content $codeScan -Raw -Encoding utf8
# Extract change info from STATE.md
$stateMd = Join-Path $ChangeDir "STATE.md"
$changeDesc = "New feature/module"
if (Test-Path $stateMd) {
    $stateContent = Get-Content $stateMd -Raw -Encoding utf8 -ErrorAction SilentlyContinue
    if ($stateContent -match "(?s)goal[:：]\s*(.+?)[\r\n]") { $changeDesc = $Matches[1].Trim() }
}
# Read requirement if exists
$reqMd = Join-Path $ChangeDir "REQUIREMENT.md"
$hasReq = Test-Path $reqMd
# Generate DESIGN.md
@"
# DESIGN

## 1. 模块边界

> 自动从 CODE_SCAN.md 提取，请复核并补充

**功能范围**：$changeDesc

**影响模块**：（从 CODE_SCAN.md 的扫描结果中提取）

**外部依赖**：（列出新增的外部依赖）

## 2. API 和权限

**REST 路径**：（设计 API 端点）

**HTTP Method**：（GET/POST/PUT/DELETE）

**权限码**：（如需新增权限码）

**匿名接口**：（是/否，默认否）

**登录态变化**：（是/否）

## 3. 数据模型和索引

**新增表/集合**：（表名和字段）

**索引**：（索引字段）

**迁移策略**：（新建迁移文件/直接修改）

## 4. 状态机

> 如不涉及，明确写"不涉及状态机"

## 5. Service 编排

**调用链**：（从 Controller 到 Repository 的完整路径）

**已有可复用 Service**：（在 CODE_SCAN.md 中查找）

## 6. 错误处理

**错误类型**：（业务异常/系统异常/参数校验）

**错误码**：（如项目有规范）

## 7. 幂等、限流、审计

**幂等策略**：（如涉及写操作）

**限流**：（如涉及公开接口）

**审计日志**：（如涉及敏感操作）

## 8. 测试策略

**单元测试**：（覆盖核心逻辑）

**集成测试**：（覆盖 API 端点）

**E2E 测试**：（如涉及用户流程）

## 9. 发布和回滚

**发布步骤**：

**回滚方案**：

## 10. 安全设计

- [ ] 输入验证（长度、类型、范围）
- [ ] 权限检查
- [ ] SQL 注入防护（参数化查询）
- [ ] XSS 防护（输出编码）
- [ ] 密钥管理（不在代码中硬编码）
- [ ] 依赖安全（npm audit / 等价）

## Design Alignment / Grill

> 待 AI 与用户对齐后填写

| 问题 | AI 推荐 | 用户确认 | 结论 |
|------|---------|---------|------|
| | | | |

**Alignment Verdict**: `pending`

---

*Generated by agent-flow generate-design.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')*
*Edit this file to reflect actual design decisions.*
"@ | Set-Content $designOut -Encoding utf8
Write-Host "✅ DESIGN.md skeleton generated: $designOut" -ForegroundColor Green
Write-Host "  Next: edit DESIGN.md, then run design-check"
