#!/usr/bin/env bash
# Generate TASKS.md from DESIGN.md
# Usage: bash agent-flow/scripts/generate-tasks.sh --change-dir <path>
set -euo pipefail
change_dir=""
while [ "$#" -gt 0 ]; do
  case "$1" in --change-dir|-ChangeDir) change_dir="$2"; shift 2 ;; *) echo "Unknown: $1"; exit 2 ;; esac
done
[ -z "$change_dir" ] && { echo "Error: --change-dir required"; exit 1; }
design="$change_dir/DESIGN.md"
tasks_out="$change_dir/TASKS.md"
[ ! -f "$design" ] && { echo "ERROR: DESIGN.md not found"; exit 1; }
[ -f "$tasks_out" ] && { echo "TASKS.md already exists"; exit 0; }
cat > "$tasks_out" << 'TASKSEOF'
# TASKS

> Generated from DESIGN.md. Edit to match actual implementation steps.

## Task List

### Task 1: Foundation/Setup

| Field | Value |
|-------|-------|
| **Status** | pending |
| **AC** | AC-01 |
| **Priority** | P0 |

**read_files**:
- (list files to read)

**write_files**:
- (list files to create/modify)

**Verification Command**:
- (command to verify)

### Task 2: Core Logic

| Field | Value |
|-------|-------|
| **Status** | pending |
| **AC** | AC-02 |
| **Priority** | P1 |

**read_files**:
- (list files)

**write_files**:
- (list files)

**Verification Command**:
- (command)

### Task 3: Verification & Report

| Field | Value |
|-------|-------|
| **Status** | pending |
| **AC** | AC-03 |
| **Priority** | P2 |

**read_files**:
- (list files)

**write_files**:
- (list files)

**Verification Command**:
- (command)

## AC-Task Mapping

| AC | Task | Verification |
|----|------|-------------|
| AC-01 | Task 1 | (verify command) |
| AC-02 | Task 2 | (verify command) |
| AC-03 | Task 3 | (verify command) |

---
*Generated by generate-tasks.sh — edit to add actual tasks*
TASKSEOF
echo "TASKS.md generated: $tasks_out"
