#!/usr/bin/env bash
# Auto-generate VERIFY.md by collecting AC evidence and check outputs
# Usage: bash agent-flow/scripts/generate-verify.sh --change-dir <path> [--project-root <path>]
set -euo pipefail
change_dir=""
project_root="."
while [ "$#" -gt 0 ]; do
  case "$1" in --change-dir|-ChangeDir) change_dir="$2"; shift 2 ;; --project-root|-ProjectRoot) project_root="$2"; shift 2 ;; *) echo "Unknown: $1"; exit 2 ;; esac
done
[ -z "$change_dir" ] && { echo "Error: --change-dir required"; exit 1; }
verify_out="$change_dir/VERIFY.md"
[ -f "$verify_out" ] && { echo "VERIFY.md already exists"; exit 0; }

# Collect ACs from TASKS.md
acs="AC-01 AC-02 AC-03"
[ -f "$change_dir/TASKS.md" ] && acs=$(grep -o 'AC-[0-9][0-9]*' "$change_dir/TASKS.md" 2>/dev/null | sort -u | tr '\n' ' ')
[ -z "$acs" ] && acs="AC-01 AC-02 AC-03"

# Run checks
ts_result="SKIP (no tsconfig.json)"
[ -f "$project_root/tsconfig.json" ] && { npx tsc --noEmit 2>/dev/null && ts_result="PASS" || ts_result="FAIL"; }
test_result="SKIP"
[ -f "$project_root/package.json" ] && { npm test 2>/dev/null && test_result="PASS" || test_result="FAIL or no tests"; }
sec_result="SKIP"
[ -f "$project_root/package.json" ] && { npm audit --audit-level=high 2>/dev/null && sec_result="PASS" || sec_result="WARN (vulnerabilities)"; }

cat > "$verify_out" << VERIFYEOF
# VERIFY

## AC Evidence

| AC | Requirement | Evidence Type | Evidence Location | Result | Residual Risk |
|----|-------------|---------------|-------------------|--------|---------------|
$(for ac in $acs; do
  echo "| $ac | (from TASKS.md) | (manual) | (file:line) | (PASS/FAIL) | (none) |"
done)

## Verification Results

| Check | Status |
|-------|--------|
| TypeScript Check | $ts_result |
| Tests | $test_result |
| Security Audit | $sec_result |
| Code Review | (pending — run /ecc-review) |
| Security Scan | (pending — run /ecc-security) |

## Manual Verification

- [ ] Code review completed (/ecc-review)
- [ ] Security review completed (/ecc-security)
- [ ] All ACs pass with evidence
- [ ] No undeclared files modified
- [ ] Edge cases tested
- [ ] Error handling verified

---
*Generated by generate-verify.sh on $(date '+%Y-%m-%d %H:%M')*
*Edit to add manual verification results.*
VERIFYEOF
echo "VERIFY.md generated: $verify_out"
echo "Next: run /ecc-review and /ecc-security, then edit evidence cells"
