<#
.SYNOPSIS
Generate REPORT.md by aggregating all change artifacts and check outputs.
.DESCRIPTION
Collects VERIFY.md findings, check results, and AC status into REPORT.md.
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$ChangeDir
)
$ErrorActionPreference = "Stop"
$report = Join-Path $ChangeDir "REPORT.md"
if (Test-Path $report) { Write-Host "REPORT.md already exists. Edit manually."; exit 0 }

# Collect artifacts
$state = Join-Path $ChangeDir "STATE.md"
$change = Join-Path $ChangeDir "CHANGE.md"
$verify = Join-Path $ChangeDir "VERIFY.md"
$tasks = Join-Path $ChangeDir "TASKS.md"
$checkResult = Join-Path $ChangeDir "CHECK_RESULT.json"
$closeResult = Join-Path $ChangeDir "CLOSURE_RESULT.json"

# Extract change description
$desc = "Unnamed change"
if (Test-Path $change) {
    $c = Get-Content $change -Raw -Encoding utf8 -ErrorAction SilentlyContinue
    if ($c -match "(?s)description[:：]\s*(.+?)[\r\n]") { $desc = $Matches[1].Trim() }
}
# Extract verification summary
$verifyFindings = @()
$verifyPass = 0; $verifyFail = 0
if (Test-Path $verify) {
    $v = Get-Content $verify -Raw -Encoding utf8 -ErrorAction SilentlyContinue
    $verifyFindings = [regex]::Matches($v, '(?m)^-\s*\[([ x])\]\s*(.+)') | ForEach-Object {
        if ($_.Groups[1].Value -eq 'x') { $verifyPass++ } else { $verifyFail++ }
        @{ status = if ($_.Groups[1].Value -eq 'x') { "PASS" } else { "FAIL" }; text = $_.Groups[2].Value }
    }
}
# Check result status
$checkStatus = "NOT RUN"
if (Test-Path $checkResult) {
    try { $j = Get-Content $checkResult -Raw | ConvertFrom-Json; $checkStatus = "PASS" } catch { $checkStatus = "FAIL" }
}
# AC status from check
$acTotal = 0; $acPass = 0
if (Test-Path $tasks) {
    $t = Get-Content $tasks -Raw -Encoding utf8 -ErrorAction SilentlyContinue
    $acMatches = [regex]::Matches($t, '(AC-\d+)')
    $acTotal = $acMatches.Count
    foreach ($m in $acMatches) { if ($t -match "$($m.Value).*PASS|$($m.Value).*Done") { $acPass++ } }
}
@"
# REPORT

## Change Summary

| Field | Value |
|-------|-------|
| **Description** | $desc |
| **Change Dir** | $ChangeDir |
| **Date** | $(Get-Date -Format 'yyyy-MM-dd HH:mm') |

## AC Coverage

| Metric | Count |
|--------|-------|
| Total ACs | $acTotal |
| Passed | $acPass |
| Coverage | $(if ($acTotal -gt 0) { "$([math]::Round($acPass/$acTotal*100))%" } else { "N/A" }) |

## Check Results

| Check | Status |
|-------|--------|
| scan-check | (pending) |
| design-check | (pending) |
| alignment-check | (pending) |
| task-check | (pending) |
| code-drift-check | (pending) |
| blocked-check | (pending) |
| task-boundary-check | (pending) |
| manifest-check | (pending) |
| evolution-check | (pending) |
| check-change | $checkStatus |

## Verification Summary

$(if ($verifyFindings.Count -gt 0) {
    $verifyFindings | ForEach-Object { "- [$($_.status)] $($_.text)" }
} else { "(No verification items recorded)" })

## Files Changed

(write_files from TASKS.md, to be filled)

## Lessons Learned

(What went well, what could be improved)

---
*Generated by generate-report.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')*
*Edit to add manual observations.*
"@ | Set-Content $report -Encoding utf8
Write-Host "REPORT.md generated: $report"
Write-Host "  AC Coverage: $acPass/$acTotal - edit to fill check results and lessons"
