#!/usr/bin/env bash
# Check for stale or expired knowledge entries in agent-flow/knowledge/.
# Usage: bash agent-flow/scripts/knowledge-expiry-check.sh [--max-age 90] [--output report.md]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
KNOWLEDGE_DIR="$ROOT/agent-flow/knowledge"
CHANGES_DIR="$ROOT/agent-flow/changes"
MAX_AGE_DAYS=90
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --knowledge-root) KNOWLEDGE_DIR="$2"; shift 2 ;;
    --max-age) MAX_AGE_DAYS="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

[ -d "$KNOWLEDGE_DIR" ] || { echo "No knowledge directory found"; exit 0; }

# ── Timestamp functions ──
current_epoch=$(date +%s)

# ── Build report ──
STALE_ROWS=""
HEALTHY_ROWS=""
STALE_COUNT=0
FRESH_COUNT=0
FILE_COUNT=0

for file in "$KNOWLEDGE_DIR"/*; do
  [ -f "$file" ] || continue
  fname="$(basename "$file")"
  [ "$fname" = ".gitkeep" ] && continue
  [ "$fname" = "INDEX.md" ] && continue

  FILE_COUNT=$((FILE_COUNT + 1))
  file_epoch=$(stat -c %Y "$file" 2>/dev/null || echo 0)
  age_days=$(( (current_epoch - file_epoch) / 86400 ))
  size_kb=$(du -k "$file" | cut -f1)

  # Check for TODO/TBD placeholders
  has_todo=false
  if grep -Eqi 'TODO|TBD|path/to|尚未|待补充' "$file" 2>/dev/null; then
    has_todo=true
  fi

  # Check if referenced in recent changes
  referenced=false
  ref_sources=""
  if [ -d "$CHANGES_DIR" ]; then
    for change_dir in "$CHANGES_DIR"/*/; do
      [ ! -d "$change_dir" ] && continue
      for doc_file in CHANGE.md REQUIREMENT.md DESIGN.md EVOLUTION.md REPORT.md; do
        doc_path="$change_dir/$doc_file"
        if [ -f "$doc_path" ] && grep -qF "$fname" "$doc_path" 2>/dev/null; then
          referenced=true
          ref_sources="$ref_sources $(basename "$change_dir")/$doc_file"
        fi
      done
    done
  fi

  # Check AGENTS.md
  AGENTS_FILE="$ROOT/AGENTS.md"
  [ -f "$AGENTS_FILE" ] && grep -qF "$fname" "$AGENTS_FILE" 2>/dev/null && referenced=true

  issues=""
  if [ "$age_days" -gt "$MAX_AGE_DAYS" ] && [ "$referenced" = false ]; then
    issues="Not referenced in ${MAX_AGE_DAYS}+ days (age: ${age_days}d)"
  fi
  if [ "$has_todo" = true ]; then
    [ -n "$issues" ] && issues="$issues; "
    issues="${issues}Contains TODO/TBD placeholders"
  fi

  if [ -n "$issues" ]; then
    STALE_COUNT=$((STALE_COUNT + 1))
    ref_text="${ref_sources:-None in recent changes}"
    STALE_ROWS="$STALE_ROWS| $fname | ${age_days}d | ${size_kb}K | $issues | $ref_text |\n"
  else
    FRESH_COUNT=$((FRESH_COUNT + 1))
    mod_date=$(date -d "@$file_epoch" '+%Y-%m-%d' 2>/dev/null || echo "unknown")
    HEALTHY_ROWS="$HEALTHY_ROWS| $fname | ${age_days}d | $mod_date |\n"
  fi
done

REPORT="# Knowledge Expiry Report

Generated: $(date '+%Y-%m-%d %H:%M')
Max age before flagging: $MAX_AGE_DAYS days
Knowledge files scanned: $FILE_COUNT
Fresh files: $FRESH_COUNT
Files with issues: $STALE_COUNT

"

if [ "$STALE_COUNT" -gt 0 ]; then
  REPORT="$REPORT
## ⚠️ Files With Issues

| File | Age | Size | Issues | References |
|------|-----|------|--------|------------|
$(echo -e "$STALE_ROWS")
"
fi

if [ "$FRESH_COUNT" -gt 0 ]; then
  REPORT="$REPORT
## ✅ Healthy Files

| File | Age | Last Modified |
|------|-----|---------------|
$(echo -e "$HEALTHY_ROWS")
"
fi

REPORT="$REPORT
## Recommendations

"
if [ "$STALE_COUNT" -gt 0 ]; then
  REPORT="$REPORT
1. Review stale files and either update them with current information or mark them as archived.
2. Remove or resolve TODO/TBD placeholders in knowledge files.
3. If a file is no longer relevant, consider archiving it with a note about its replacement.
"
else
  REPORT="$REPORT
All knowledge files are current and referenced. No action needed.
"
fi

REPORT="$REPORT
---
*Generated by knowledge-expiry-check.sh*
"

if [ -n "$OUTPUT" ]; then
  echo -e "$REPORT" > "$OUTPUT"
  echo "Report written to: $OUTPUT"
else
  echo -e "$REPORT"
fi
