#!/usr/bin/env bash
# Auto-suggest knowledge base updates based on pattern analysis and change history.
# Usage: bash agent-flow/scripts/knowledge-suggest.sh [--output report.md]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
KNOWLEDGE_DIR="$ROOT/agent-flow/knowledge"
CHANGES_DIR="$ROOT/agent-flow/changes"
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

[ -d "$KNOWLEDGE_DIR" ] || { echo "No knowledge directory found"; exit 0; }

# ── Scan for new terms and pitfalls ──
NEW_TERMS=""
NEW_PITFALLS=""
CHANGE_COUNT=0

if [ -d "$CHANGES_DIR" ]; then
  for change_dir in "$CHANGES_DIR"/*/; do
    [ ! -d "$change_dir" ] && continue
    CHANGE_COUNT=$((CHANGE_COUNT + 1))
    change_id="$(basename "$change_dir")"

    # Check REQUIREMENT.md for new terms
    REQ_FILE="$change_dir/REQUIREMENT.md"
    if [ -f "$REQ_FILE" ]; then
      # Extract term tables — look for AC-related terms
      while IFS='|' read -r _ term def _ deposited _; do
        term_t=$(echo "$term" | xargs)
        def_t=$(echo "$def" | xargs)
        [ -z "$term_t" ] && continue
        [ "$term_t" = "术语" ] && continue
        deposited_t=$(echo "$deposited" | xargs)
        # Check if not yet deposited and not already in our list
        if ! echo "$deposited_t" | grep -qi "是"; then
          if ! echo "$NEW_TERMS" | grep -qF "$term_t"; then
            NEW_TERMS="$NEW_TERMS| $term_t | $def_t | $change_id |\n"
          fi
        fi
      done < <(grep '|' "$REQ_FILE" | grep -v '---' | head -20)
    fi

    # Check EVOLUTION.md for pitfalls
    EVO_FILE="$change_dir/EVOLUTION.md"
    if [ -f "$EVO_FILE" ]; then
      # Look for non-empty bullets in problem sections
      while IFS= read -r line; do
        if echo "$line" | grep -Eq '^\s*-\s+' && ! echo "$line" | grep -Eq '无|none'; then
          candidate=$(echo "$line" | sed 's/^\s*-\s*//')
          [ -n "$candidate" ] && [ ${#candidate} -gt 10 ] && \
            NEW_PITFALLS="$NEW_PITFALLS| $candidate | $change_id |\n"
        fi
      done < <(sed -n '/暴露的问题/,/应写入知识/p' "$EVO_FILE" 2>/dev/null || true)
    fi
  done
fi

# ── Build report ──
REPORT="# Knowledge Suggestion Report

Generated: $(date '+%Y-%m-%d %H:%M')
Changes scanned: $CHANGE_COUNT

"

if [ -n "$NEW_TERMS" ]; then
  REPORT="$REPORT
## 📝 Suggested Glossary Additions

| Term | Definition | Source Change |
|------|------------|---------------|
$(echo -e "$NEW_TERMS")
"
else
  REPORT="$REPORT
## ✅ No New Glossary Terms

All terms from recent changes are already deposited in glossary.md.

"
fi

if [ -n "$NEW_PITFALLS" ]; then
  REPORT="$REPORT
## ⚠️ Suggested Pitfalls Additions

| Suggested Pitfall | Source Change |
|-------------------|---------------|
$(echo -e "$NEW_PITFALLS" | sort -u)

Format to add to pitfalls.md:

\`\`\`markdown
### [pitfall name]

- **What**: [description]
- **Why it happens**: [root cause]
- **How to prevent**: [solution]
- **Detection**: [how to check]
\`\`\`

"
else
  REPORT="$REPORT
## ✅ No Recurring Pitfalls Detected

"
fi

REPORT="$REPORT
## Recommendations

- Review suggested glossary terms and add to \`glossary.md\`
"

if [ -n "$NEW_PITFALLS" ]; then
  REPORT="$REPORT
- Review suggested pitfalls and add to \`pitfalls.md\`
"
fi

REPORT="$REPORT
- Run \`bash agent-flow/scripts/pattern-discovery.sh\` for deeper pattern analysis

---
*Generated by knowledge-suggest.sh*
"

if [ -n "$OUTPUT" ]; then
  echo -e "$REPORT" > "$OUTPUT"
  echo "Report written to: $OUTPUT"
else
  echo -e "$REPORT"
fi
