#!/usr/bin/env bash
# Detect drift between project structure and agent-flow/manifest.yaml.
# Usage: bash agent-flow/scripts/manifest-drift-check.sh [--output report.md]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MANIFEST="$ROOT/agent-flow/manifest.yaml"
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

[ -f "$MANIFEST" ] || { echo "No manifest.yaml found"; exit 0; }

# ── Detect project structure ──
has_file() { [ -f "$ROOT/$1" ]; }

BUILD_DETECTED="unknown"
LANG_DETECTED="unknown"
FE_DETECTED="none"
HAS_DB=false
MISMATCHES=""

has_file "pom.xml" && { BUILD_DETECTED="Maven"; LANG_DETECTED="Java"; }
has_file "build.gradle" && { BUILD_DETECTED="Gradle"; LANG_DETECTED="Java/Kotlin"; }
has_file "pyproject.toml" && { BUILD_DETECTED="Python"; LANG_DETECTED="Python"; }
has_file "go.mod" && { BUILD_DETECTED="Go"; LANG_DETECTED="Go"; }
has_file "Cargo.toml" && { BUILD_DETECTED="Cargo"; LANG_DETECTED="Rust"; }

if has_file "package.json"; then
  FE_DETECTED="Node/Web"
  grep -q '"vue"' "$ROOT/package.json" 2>/dev/null && FE_DETECTED="Vue"
  grep -q '"react"' "$ROOT/package.json" 2>/dev/null && FE_DETECTED="React"
  grep -q '"next"' "$ROOT/package.json" 2>/dev/null && FE_DETECTED="Next.js"
fi

for d in migrations schema sql db database prisma sequelize typeorm; do
  [ -d "$ROOT/$d" ] && HAS_DB=true
done

# ── Extract manifest values ──
MANIFEST_BUILD=$(grep -E '^\s+build:' "$MANIFEST" | sed 's/.*build:[[:space:]]*//' | tr -d ' ')
MANIFEST_LANG=$(grep -E '^\s+language:' "$MANIFEST" | sed 's/.*language:[[:space:]]*//' | tr -d ' ')
MANIFEST_FE=$(grep -E '^\s+framework:' "$MANIFEST" | head -1 | sed 's/.*framework:[[:space:]]*//' | tr -d ' ')
MANIFEST_DB=$(grep -A1 '^\s\?database:' "$MANIFEST" | grep 'engine:' | sed 's/.*engine:[[:space:]]*//' | tr -d ' ')
MANIFEST_FE_VERIFY=$(grep 'verify_required:' "$MANIFEST" | sed 's/.*verify_required:[[:space:]]*//' | tr -d ' ')

# ── Detect mismatch ──
[ "$BUILD_DETECTED" != "unknown" ] && [ "$MANIFEST_BUILD" != "$BUILD_DETECTED" ] && \
  MISMATCHES="$MISMATCHES\n- Build system: manifest says '$MANIFEST_BUILD', detected '$BUILD_DETECTED'"

[ "$FE_DETECTED" != "none" ] && [ "$MANIFEST_FE" = "none" ] && \
  MISMATCHES="$MISMATCHES\n- Frontend: package.json detected but manifest says '$MANIFEST_FE'"

[ "$HAS_DB" = true ] && [ "$MANIFEST_DB" = "none" ] && \
  MISMATCHES="$MISMATCHES\n- Database: migration/schema dirs exist but manifest says '$MANIFEST_DB'"

# ── Build report ──
REPORT="# Manifest Drift Report

Generated: $(date '+%Y-%m-%d %H:%M')
Project: $(basename "$ROOT")

## Detected Project State

| Aspect | Detected | Manifest Says |
|--------|----------|--------------|
| Build system | $BUILD_DETECTED | $MANIFEST_BUILD |
| Language | $LANG_DETECTED | $MANIFEST_LANG |
| Frontend | $FE_DETECTED | $MANIFEST_FE |
"

if [ -n "$MISMATCHES" ]; then
  REPORT="$REPORT
## ⚠️ Drift Detected
$(echo -e "$MISMATCHES")

## Recommended Actions
1. Run \`bash agent-flow/scripts/init-wizard.sh\` to re-initialize manifest.yaml
2. Or manually update \`agent-flow/manifest.yaml\` to match actual project structure
3. Run \`bash agent-flow/scripts/manifest-check.sh\` after updating
"
else
  REPORT="$REPORT
## ✅ No Drift Detected

Project structure matches manifest.yaml. No updates needed.
"
fi

REPORT="$REPORT
---
*Generated by manifest-drift-check.sh*
"

if [ -n "$OUTPUT" ]; then
  echo -e "$REPORT" > "$OUTPUT"
  echo "Report written to: $OUTPUT"
else
  echo -e "$REPORT"
fi
