#!/usr/bin/env bash
# Discover recurring patterns across EVOLUTION.md files.

set -euo pipefail

changes_root="agent-flow/changes"
min_occurrences=2
output=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --changes-root) changes_root="$2"; shift 2 ;;
    --min-occurrences) min_occurrences="$2"; shift 2 ;;
    --output) output="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: pattern-discovery.sh [--changes-root agent-flow/changes] [--min-occurrences 2] [--output report.md]"
      exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/../.." && pwd)"
changes_dir="$root/$changes_root"
knowledge_dir="$root/agent-flow/knowledge"

if [ ! -d "$changes_dir" ]; then
  echo "No changes directory found at $changes_dir"
  exit 0
fi

patterns=(
  "documentation_gap|knowledge|documentation,missing doc,unclear"
  "test_coverage_gap|gate|test coverage,untested,no test"
  "boundary_violation|gate|boundary,write_files,unauthorized"
  "schema_risk|audit|schema,migration,database"
  "permission_risk|audit|permission,auth,role"
  "api_contract_break|gate|api,contract,breaking"
  "state_machine_complexity|design|state machine,workflow"
  "knowledge_not_captured|knowledge|knowledge,glossary,pitfall"
  "template_gap|process|template,missing field,artifact"
  "process_bypass|process|bypass,skip process"
)

declare -A counts
declare -A changes
declare -A categories
changes_scanned=0
evolution_files=0

for change_dir in "$changes_dir"/*/; do
  [ -d "$change_dir" ] || continue
  changes_scanned=$((changes_scanned + 1))
  evo_file="$change_dir/EVOLUTION.md"
  [ -f "$evo_file" ] || continue
  evolution_files=$((evolution_files + 1))
  change_name="$(basename "$change_dir")"
  evo_text="$(tr '[:upper:]' '[:lower:]' < "$evo_file")"

  for def in "${patterns[@]}"; do
    IFS='|' read -r name category keywords <<< "$def"
    categories["$name"]="$category"
    IFS=',' read -ra keyword_list <<< "$keywords"
    for keyword in "${keyword_list[@]}"; do
      if printf '%s\n' "$evo_text" | grep -Fqi "$keyword"; then
        counts["$name"]=$(( ${counts["$name"]:-0} + 1 ))
        changes["$name"]="${changes["$name"]:-} $change_name"
        break
      fi
    done
  done
done

existing_pitfalls=""
[ -f "$knowledge_dir/pitfalls.md" ] && existing_pitfalls="$(cat "$knowledge_dir/pitfalls.md")"

report="# Pattern Discovery Report

Generated: $(date '+%Y-%m-%d %H:%M')
Min occurrences to flag: $min_occurrences
Changes scanned: $changes_scanned
EVOLUTION.md files found: $evolution_files
"

if [ "${#counts[@]}" -eq 0 ]; then
  report="$report
## No Patterns Detected

No EVOLUTION.md files found or no patterns matched.
"
else
  report="$report
## All Detected Patterns

| Pattern | Category | Occurrences | Affected Changes |
|---------|----------|-------------|------------------|
"
  recurring=""
  for name in "${!counts[@]}"; do
    count="${counts[$name]}"
    category="${categories[$name]:-unknown}"
    affected="$(printf '%s\n' ${changes[$name]} | sort -u | paste -sd ', ' -)"
    if [ "$count" -ge "$min_occurrences" ]; then
      report="$report| **$name** | $category | **$count** | $affected |
"
      action="consider adding to knowledge/pitfalls.md"
      if printf '%s\n' "$existing_pitfalls" | grep -Fqi "$name"; then
        action="already captured"
      fi
      recurring="$recurring
### $name ($count times)

- Category: $category
- Affected changes: $affected
- Suggested action: $action
"
    else
      report="$report| $name | $category | $count | $affected |
"
    fi
  done

  if [ -n "$recurring" ]; then
    report="$report
## Recurring Patterns
$recurring
"
  fi
fi

report="$report
---
*Generated by pattern-discovery.sh*
"

if [ -n "$output" ]; then
  printf '%s\n' "$report" > "$output"
  echo "Report written to: $output"
else
  printf '%s\n' "$report"
fi
